name: Advanced Secret Scanner

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - run: pip install requests

      - run: python secret_bot.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}